### ISSUE TITLE
WindowCenteringHelper 3x Shift doesn't work.

### ISSUE THREAD

**Issue by Trendle** [KamilSzymborski/kamilszymborski.github.io#1]
Hello, your window centering program doesn't work for me. I'm using Windows 7 x64 and 200% DPI scaling.

Automatic centering works, but not the 3x Shift function.

**Comment by Trendle** [comment]
Automatic centering works, but not the 3x Shift function.

**Comment by KamilSzymborski** [comment]
Hi thanks for the feedback.

Well, I have no idea what could be the reason :)

With "RShift": 
[WCH-RShift.zip](https://github.com/KamilSzymborski/kamilszymborski.github.io/files/4681822/WCH-RShift.zip)
