### ISSUE TITLE
WindowCenteringHelper: Center position calculation is incorrect

### ISSUE THREAD

**Issue by wafihartono** [KamilSzymborski/kamilszymborski.github.io#3]
The offset is -6px (6px higher than correct position). Here's my [screenshot](https://imgur.com/a/oWEJwvG).

For reference my PC's resolution is 1366x768px and the taskbar size is 30px. I'm using small taskbar.

**Comment by KamilSzymborski** [comment]
Everything is fine.

The work area is dynamically calculated.

Your "6px" de facto still belongs to the application you show - it depends on the technology used.

See how the "Telegram" application is centered: [screenshot](https://ibb.co/rwCZr71)

Now the application "Edge" with the same fixed size : [screenshot](https://ibb.co/GpWtsS4)

**Comment by wafihartono** [comment]
Huh, maybe that explains why some apps have different position while having the same size.

Alright then, I'm closing this issue. Thanks.

**Comment by KamilSzymborski** [comment]
I "fixed" it in my private version (it turned out to be possible). I also added a blacklist, but I don't feel like publishing.

I'm waiting for what Windows 11 will bring - maybe window centering :>
